### ISSUE TITLE
URL changes?

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/nekovm.org#1]
See https://github.com/travis-ci/travis-ci/issues/4583
Would you make the old urls work soonish as TravisCI haxe builds depend on them.

**Comment by andyli** [comment]
ping @jasononeil

**Comment by jasononeil** [comment]
Sorry about that :(  I thought I had it right but I think the "_media" address was some kind of dokuwiki crazy redirect scheme.  I've updated it now.

**Comment by jasononeil** [comment]
The "_media/" URLs are working again, but Travis is still failing - despite the same curl command working perfectly on my machines.  I'm going to close this and keep track of it in https://github.com/travis-ci/travis-ci/issues/4583 @andyli if you have any ideas let me know asap.  I'll stay on #haxe IRC and Google Chat if you want to talk it through

**Comment by jasononeil** [comment]
Turns out they are passing, the log message I was viewing just hadn't updated.  Problem solved I think.  Thanks @andyli

**Comment by andyli** [comment]
Just checked that it has been fixed, thanks @jasononeil : )
