### ISSUE TITLE
Neko Mailing List links are broken

### ISSUE THREAD

**Issue by bsaleil** [HaxeFoundation/nekovm.org#10]
As title said, links to the Neko mailing list at http://nekovm.org/ml are all dead :(

**Comment by markknol** [comment]
It's already fixed here but not put online yet https://github.com/HaxeFoundation/nekovm.org/pull/8

**Comment by bsaleil** [comment]
ok thanks

**Comment by markknol** [comment]
Let's keep it open until it's online :smile:

**Comment by andyli** [comment]
It's online now ;)

**Comment by markknol** [comment]
Great! Good job!
