### ISSUE TITLE
Adding examples to the website

### ISSUE THREAD

**Issue by amTrouzine** [HaxeFoundation/nekovm.org#13]
It seems interesting that nekoVm is lightweight, embeddable and faster than many languages...
It would be appreciable if it's possible to add examples for making this language popular and easy to learn.
The َAutoIt or actionScript help files are good models.
The purpose (from this issue...) is to teach newbies and beginner users first , not the developers and/or advanced users
Regards,

**Comment by Jeeppler** [comment]
The Haxe programming language can compile to Neko.

**Comment by Simn** [comment]
Yes, that's the preferred way to use neko.
