### ISSUE TITLE
[Feature request] Add actual bytecode specification to Virtual Machine docs

### ISSUE THREAD

**Issue by gamemanj** [HaxeFoundation/nekovm.org#14]
Neko (the language) is, if I'm reading this correctly, meant to be used as a compiler target.
However, before actually being executed, it has to be run through nekoc (a NekoML program).
The output of nekoc is useful, as there is little room for error when interpreting it, or possibility for unimplemented feature ambiguity (like NXML).
Furthermore, there is always the case of people, for whatever reason, shipping ".n" binaries (such as the bootstrap binaries that come with the source of Neko - even assuming nekoc is useless for a VM, NekoML can export to the Neko intermediate form, so running it would be useful - but you can't run NekoML without NekoML or a way to execute the NekoML .n file...), so even a VM that starts from Neko is going to encounter issues.

The Virtual Machine docs don't actually describe the Virtual Machine. They describe the implementation of the Virtual Machine and how to communicate it, which is certainly useful, but doesn't actually give any way for prospective implementors to write an interpreter.
They instead have to go searching through the existing interpreter for the information (specific points of interest are module.c and interp.c), which is not ideal.

For these reasons (and presumably you can work out more), it would be nice to have documentation on the ".n" format, the bytecode compression and the actual instruction formats in the file.
(Another note: There is also no table, anywhere that I know, that directly puts numbers to the names of the opcodes. It's all implied by C enums.)

**Comment by ncannasse** [comment]
I don't have much time to document the NekoVM bytecode, but you can find a reference implementation for reading it there: https://github.com/HaxeFoundation/format/tree/master/format/neko
