### ISSUE TITLE
Turn it into a static site

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/nekovm.org#15]
Pretty much like haxe.org, there is no need to use ufront for this simple web site...
@ibilon Would you do the conversion just like you did for haxe.org?

**Comment by ibilon** [comment]
Sure.

I started, shouldn't take long, the website is small and I can use code from haxe.org.

**Comment by andyli** [comment]
Any progress? ;)

**Comment by ibilon** [comment]
Forgot about that ^^'
I'll do it soon ;)

**Comment by andyli** [comment]
Ping again since I will release a new version of neko soonish.

**Comment by ibilon** [comment]
I should never say "soon" ever again :D

It's on the branch https://github.com/HaxeFoundation/nekovm.org/tree/static,
took a couple liberties so that the sitemap would be better.

Could also use a download page similar to the one for haxe.org, but that can be added later.

**Comment by andyli** [comment]
Thanks! I'm checking it out now.
Will probably just merge it :)

**Comment by andyli** [comment]
Merged to master, and the page can be viewed at https://d2k5fzddpe7f67.cloudfront.net/. Waiting for Nicolas for the DNS access.
The GitHub pages url, http://haxefoundation.github.io/nekovm.org/,  wouldn't work since the site is not at the root domain.

**Comment by ncannasse** [comment]
Done

**Comment by andyli** [comment]
@ncannasse I can see that you've approved the ssl cert, but I still need the DNS access.
I think you gave me the DNS access in the past, but somehow I couldn't find it (currently I only use aws route53 since I transferred haxe.org to there).
May I have the DNS access again such that I can config nekovm.org to point to github pages?

**Comment by andyli** [comment]
All done :)
