### ISSUE TITLE
Host binaries on github releases

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/nekovm.org#18]
We could consider hosting the binaries for Neko using Github releases, the way we do it for Haxe too.
https://github.com/HaxeFoundation/neko/releases

**Comment by andyli** [comment]
I've just uploaded the binaries to GitHub pages. The next step would be to redirect the old links to there.

**Comment by andyli** [comment]
Fixed along with #15.

**Comment by back2dos** [comment]
Could you please take care of those redirects? Virtually all my builds just broke.

**Comment by andyli** [comment]
Sorry but there is no real redirect support in GitHub pages. In where do you make use of the urls?

**Comment by back2dos** [comment]
These urls are used by [switchx](https://github.com/lix-pm/switchx) and [nvm](https://github.com/dpeek/hvm/blob/0c7ea12a2fdde7997f0a9d9e036ca5c22aeefd64/config.sh#L69) to download neko.

If gh pages doesn't support redirects, would you consider uploading [just the three files switchx was using](https://github.com/lix-pm/switchx/blob/f6bfd7e0a6983751a0a1fe79be934f9d4d66f755/src/switchx/Cli.hx#L53)? It's only a couple of MB and it seems to be the least amount of trouble. I published a new version of switchx but I'd still have to go through ~40 projects to actually make them use it.

**Comment by andyli** [comment]
Oh wait, we're using cloudfront which has a way to do it. give me a couple of minutes.

**Comment by andyli** [comment]
The 2.1.0 Linux and Mac binaries should be in place. The others are still uploading - my home Internet connection is pretty slow.

Extra care is taken to make the links work even if the client doesn't support http redirect (e.g. haxe.Http and curl without -L).

**Comment by back2dos** [comment]
Awesome! Thanks a lot ;)
