### ISSUE TITLE
64bit mac build

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/nekovm.org#2]
When testing out TravisCI haxe support for OSX builds, I noticed that our haxe OSX binaries archive is 64bit. But the nekovm website only provides 32bit neko...
It has been [a problem](https://groups.google.com/forum/#!topic/haxelang/EQCBwA5H67o) for quite some time.

The weird thing is, the haxe OSX installer does install a 64-bit neko... So why not put the 64-bit neko on the neko website? ;)

Here below is the 64-bit neko archive extracted from our official haxe mac installer:
https://dl.dropboxusercontent.com/u/2661116/neko-2.0.0-osx64.tar.gz

**Comment by andyli** [comment]
Any opinion, @ncannasse?

**Comment by ncannasse** [comment]
We could host it (ask @jasononeil) or wait until we release 2.1

**Comment by andyli** [comment]
Great! I prefer to have it hosted now since TravisCI haxe support depends on it.

@jasononeil Would you help us to host it?

**Comment by andyli** [comment]
@jasononeil Hey! It has been about 2 weeks since my last comment. Do you have anytime to upload the archive to the server? You may list it in the website later, but I need the archive to be officially hosted such that I can update the Travis haxe support.

**Comment by jasononeil** [comment]
Sorry @andyli for the delay...

It's uploaded at http://nekovm.org/media/neko-2.0.0-osx64.tar.gz

I'll add the link to the website a bit later.

**Comment by andyli** [comment]
Thanks! :)
